name: riverpod_skeleton
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.7.0
description: A new Flutter project.
dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_form_builder: ^10.2.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.1
  form_builder_validators: ^11.2.0
  go_router: ^16.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.6.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  pubspec_dependency_sorter: ^1.0.5
  retrofit_generator: ^9.7.0
  riverpod_generator: ^2.6.5
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
flutter_intl:
  enabled: true

##Use flutter pub run pubspec_dependency_sorter
#to sort the dependencies by Alphabetical
